import { AttributeKey, CharacterSheetData, Skill } from './types';

export const ATTRIBUTE_LABELS: Record<AttributeKey, string> = {
  for: 'Força',
  des: 'Destreza',
  con: 'Constituição',
  int: 'Inteligência',
  sab: 'Sabedoria',
  car: 'Carisma',
};

export const INITIAL_SKILLS: Record<string, Skill> = {
  acrobacia: { name: 'Acrobacia', attr: 'des', proficient: false, expertise: false },
  arcanismo: { name: 'Arcanismo', attr: 'int', proficient: false, expertise: false },
  atletismo: { name: 'Atletismo', attr: 'for', proficient: false, expertise: false },
  atuacao: { name: 'Atuação', attr: 'car', proficient: false, expertise: false },
  enganacao: { name: 'Enganação', attr: 'car', proficient: false, expertise: false },
  furtividade: { name: 'Furtividade', attr: 'des', proficient: false, expertise: false },
  historia: { name: 'História', attr: 'int', proficient: false, expertise: false },
  intimidacao: { name: 'Intimidação', attr: 'car', proficient: false, expertise: false },
  intuicao: { name: 'Intuição', attr: 'sab', proficient: false, expertise: false },
  investigacao: { name: 'Investigação', attr: 'int', proficient: false, expertise: false },
  lidar_animais: { name: 'Lidar com Animais', attr: 'sab', proficient: false, expertise: false },
  medicina: { name: 'Medicina', attr: 'sab', proficient: false, expertise: false },
  natureza: { name: 'Natureza', attr: 'int', proficient: false, expertise: false },
  percepcao: { name: 'Percepção', attr: 'sab', proficient: false, expertise: false },
  persuasao: { name: 'Persuasão', attr: 'car', proficient: false, expertise: false },
  prestidigitacao: { name: 'Prestidigitação', attr: 'des', proficient: false, expertise: false },
  religiao: { name: 'Religião', attr: 'int', proficient: false, expertise: false },
  sobrevivencia: { name: 'Sobrevivência', attr: 'sab', proficient: false, expertise: false },
  tecnologia: { name: 'Tecnologia', attr: 'int', proficient: false, expertise: false },
};

export const DEFAULT_CHARACTER: CharacterSheetData = {
  info: {
    playerName: '',
    charName: '',
    origin: '',
    region: '',
    background: '',
    essence: '',
    classLevel: '',
    level: 1,
    xp: '',
  },
  attributes: {
    for: { value: 10, modifier: 0 },
    des: { value: 10, modifier: 0 },
    con: { value: 10, modifier: 0 },
    int: { value: 10, modifier: 0 },
    sab: { value: 10, modifier: 0 },
    car: { value: 10, modifier: 0 },
  },
  skills: INITIAL_SKILLS,
  vitals: {
    hpCurrent: '',
    hpMax: '',
    hpTemp: '',
    hitDice: '',
    hitDiceTotal: '',
    ac: 10,
    initiative: 0,
    speed: '9m',
    proficiencyBonus: 2,
    inspiration: false,
    passivePerception: 10,
    passiveInsight: 10,
  },
  savingThrows: {
    for: false,
    des: false,
    con: false,
    int: false,
    sab: false,
    car: false,
  },
  attacks: [
    { 
      id: '1', 
      name: '', 
      description: '',
      accAttr1: 'for', accAttr2: 'none', accProf: true, accBonuses: [],
      dmgAttr1: 'for', dmgAttr2: 'none', dmgDice: '', dmgType: '', dmgBonuses: []
    }
  ],
  spells: [],
  runes: '',
  features: [],
  equipment: [],
  languages: [],
  proficiencies: [],
  notes: [],
  deathSaves: { success: 0, failure: 0 },
  exhaustion: 0,
  mana: { current: '', max: '' },
  spellSaveDC: '',
  spellAttack: '',
  runeDC: '',
  runeAttack: '',
};